/** Source-backed FSP requirement register and manual review queue inside the Legal OS shell. */
import Link from 'next/link'
import { ArrowLeft, ChevronDown, FileSearch, ListFilter } from 'lucide-react'
import { requireSession } from '@/lib/auth'
import { requireGlobalDocumentAccess } from '@/lib/document-access'
import { getFspComplianceDashboard } from '@/lib/fsp-compliance/service'
import type { FspComplianceDashboard } from '@/lib/fsp-compliance/types'
import { EntityField, fieldClass } from '@/components/legal/entity-fields'
import { EntityActionForm } from '@/components/legal/entity-action-form'
import { queueFspComplianceControl } from '@/actions/fsp-compliance'
import { DecisionForm, FactForm, RuleSourceForm } from './review-fields'
import { DetailField, displayDate, displayState, EvidenceLink, StateLabel } from './presentation'

type Finding = FspComplianceDashboard['findings'][number]
type SearchParams = Record<string, string | string[] | undefined>
const STATUSES = ['NEEDS_FACTS', 'LEGAL_REVIEW', 'APPLICABLE', 'NOT_APPLICABLE'] as const
const PRIORITIES = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] as const

function queryValue(params: SearchParams, key: string) {
  return typeof params[key] === 'string' ? params[key].trim().slice(0, 200) : ''
}

function FindingDetails({ finding, dashboard }: { finding: Finding; dashboard: FspComplianceDashboard }) {
  const { rule, evaluation, decision } = finding
  const facts = dashboard.facts.filter((fact) => evaluation.factKeys.includes(fact.key))
  const sources = dashboard.sources.filter((source) => rule.sourceIds.includes(source.id))
  return <div className="space-y-6 border-t border-border bg-muted/10 px-4 py-5 sm:px-5">
    <div className="grid gap-6 lg:grid-cols-2">
      <section className="space-y-3"><h3 className="text-sm font-semibold">Why this needs review</h3><p className="text-sm leading-relaxed">{rule.summary}</p>
        <dl className="grid grid-cols-2 gap-4"><DetailField label="Basis">{displayState(rule.basis)}</DetailField><DetailField label="Jurisdiction">{rule.jurisdiction}</DetailField><DetailField label="Effective from">{rule.effectiveFrom ? displayDate(rule.effectiveFrom) : 'Requires legal confirmation'}</DetailField><DetailField label="Effective through">{rule.effectiveTo ? displayDate(rule.effectiveTo) : 'No end date recorded'}</DetailField><DetailField label="Rule timing">{displayState(evaluation.timing)}</DetailField><DetailField label="Rule review date">{displayDate(rule.reviewOn)}</DetailField></dl>
        <ul className="space-y-3 border-t border-border pt-3">{sources.map((source) => <li key={source.id} className="text-sm"><EvidenceLink url={source.url}>{source.title}</EvidenceLink><p className="mt-1 text-xs text-muted-foreground">{displayState(source.kind)} · Checked {displayDate(source.checkedAt)}</p>{source.note && <p className="mt-1 text-xs leading-relaxed text-muted-foreground">{source.note}</p>}</li>)}</ul>
        {dashboard.canWrite && dashboard.snapshotId && <details className="border-t border-border pt-3"><summary className="cursor-pointer text-xs text-primary">Update rule source review</summary><RuleSourceForm snapshotId={dashboard.snapshotId} finding={finding} /></details>}
      </section>
      <section className="space-y-3"><h3 className="text-sm font-semibold">Policy and control work</h3><ol className="list-decimal space-y-2 pl-5 text-sm leading-relaxed">{rule.actions.map((action, index) => <li key={`${rule.id}-action-${index}`}>{action}</li>)}</ol>
        <div className="border-t border-border pt-3"><p className="text-xs text-muted-foreground">Implementation evidence</p><p className="mt-1 whitespace-pre-wrap break-words text-sm">{decision?.evidenceReference || 'Not supplied. Listed policy work is a review requirement, not an approved policy.'}</p><Link href="/legal/policies" className="mt-2 inline-block text-xs text-primary underline-offset-4 hover:underline">Open Policies &amp; Procedures</Link></div>
      </section>
    </div>
    <section className="space-y-3 border-t border-border pt-4"><h3 className="text-sm font-semibold">Feature context and missing facts</h3><p className="text-xs leading-relaxed text-muted-foreground">Source capability is separate from verified production behavior. The rule trigger currently evaluates to {displayState(evaluation.truth).toLowerCase()}.</p>
      <div className="grid gap-4 md:grid-cols-2">{facts.map((fact) => <div key={fact.key} className="min-w-0 border-l-2 border-border pl-3"><a href={`#fact-${fact.key}`} className="text-sm font-medium text-primary underline-offset-4 hover:underline">{fact.label}</a><p className="mt-1 text-xs text-muted-foreground">{displayState(fact.value)} · {fact.certainty === 'SOURCE_SIGNAL' ? 'Source capability only' : displayState(fact.certainty)}{evaluation.staleFactKeys.includes(fact.key) ? ' · Review expired' : ''}</p><p className="mt-2 text-sm leading-relaxed">{fact.detail}</p></div>)}</div>
      {!!evaluation.missingFactKeys.length && <p className="text-xs text-warning">{evaluation.missingFactKeys.length} triggering {evaluation.missingFactKeys.length === 1 ? 'fact needs' : 'facts need'} evidence before a conclusive applicability decision.</p>}
    </section>
    <section className="space-y-3 border-t border-border pt-4"><h3 className="text-sm font-semibold">Legal review</h3>
      {decision ? <div className="space-y-3"><p className="text-xs text-muted-foreground">Recorded {displayDate(decision.createdAt)} by {decision.actor}{decision.stale ? ' · Earlier evidence, review again' : ''}</p><p className="whitespace-pre-wrap break-words text-sm leading-relaxed">{decision.reason}</p><p className="whitespace-pre-wrap break-words text-xs text-muted-foreground">Source: {decision.sourceReference}</p><p className="text-xs text-muted-foreground">Evidence checked {displayDate(decision.evidenceAsOf)}</p></div> : <p className="text-sm text-muted-foreground">No human applicability decision recorded.</p>}
      <dl className="grid grid-cols-2 gap-4"><DetailField label="Owner">{decision?.owner || 'Unassigned'}</DetailField><DetailField label="Next legal review">{decision ? displayDate(decision.reviewOn) : 'Not set'}</DetailField></dl>
      {dashboard.canWrite && dashboard.assessmentId && <details className="pt-2"><summary className="cursor-pointer text-sm font-medium text-primary">Record a legal review</summary><DecisionForm key={decision?.id ?? dashboard.assessmentId} assessmentId={dashboard.assessmentId} finding={finding} /></details>}
      {(finding.sync || (dashboard.cisoEnabled && decision?.status === 'APPLICABLE' && !decision.stale)) && <div className="border-t border-border pt-3"><p className="text-xs font-medium">{decision?.stale ? 'Historical CISO delivery receipt' : 'CISO control synchronization'}</p>{finding.sync ? <p className="mt-2 text-xs text-muted-foreground"><StateLabel value={finding.sync.status} />{finding.sync.completedAt ? ` · Completed ${displayDate(finding.sync.completedAt)}` : ' · No delivery receipt yet'}{finding.sync.errorCode ? ` · ${displayState(finding.sync.errorCode)}` : ''}</p> : <p className="mt-2 text-xs text-muted-foreground">This approved requirement has not been queued.</p>}{dashboard.canWrite && dashboard.cisoEnabled && decision?.status === 'APPLICABLE' && !decision.stale && <EntityActionForm action={queueFspComplianceControl} submitLabel="Queue approved control"><input type="hidden" name="decisionId" value={decision.id} /></EntityActionForm>}</div>}
      {!!finding.history.length && <details className="pt-2"><summary className="cursor-pointer text-xs text-muted-foreground">Review history ({finding.history.length})</summary><div className="mt-3 divide-y divide-border">{finding.history.map((review) => <article key={review.id} className="space-y-2 py-3"><p className="text-xs">{displayDate(review.createdAt)} · {review.actor} · <StateLabel value={review.status} />{review.stale ? ' · Superseded evidence' : ''}</p><p className="whitespace-pre-wrap break-words text-sm">{review.reason}</p><p className="whitespace-pre-wrap break-words text-xs text-muted-foreground">Source: {review.sourceReference}</p><p className="text-xs text-muted-foreground">Control: {displayState(review.controlStatus)} · Review due {displayDate(review.reviewOn)}</p>{review.evidenceReference && <p className="whitespace-pre-wrap break-words text-xs">Evidence: {review.evidenceReference}</p>}</article>)}</div></details>}
    </section>
  </div>
}

export default async function FspCompliancePage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const session = await requireSession()
  await requireGlobalDocumentAccess(session)
  const [dashboard, params] = await Promise.all([getFspComplianceDashboard(session), searchParams])
  const status = queryValue(params, 'status'), priority = queryValue(params, 'priority'), category = queryValue(params, 'category'), search = queryValue(params, 'q')
  const findings = dashboard.findings.filter((finding) => (!status || finding.status === status) && (!priority || finding.rule.priority === priority) && (!category || finding.rule.category === category) && (!search || `${finding.rule.title} ${finding.rule.summary} ${finding.rule.actions.join(' ')} ${finding.rule.jurisdiction}`.toLowerCase().includes(search.toLowerCase())))
  const categories = [...new Set(dashboard.findings.map((finding) => finding.rule.category))].sort()
  return <div className="space-y-7">
    <header className="space-y-4"><Link href="/legal/compliance" className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="h-3 w-3" aria-hidden="true" />All compliance</Link><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">FSP app compliance</h1><p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">Requirements, missing facts and policy work for the FSP app. Applicability decisions and implementation evidence are tracked separately.</p></div><EvidenceLink url="https://app.futureofsports.io">Open FSP app</EvidenceLink></div>
      <p className="border-l-2 border-warning pl-3 text-sm text-warning">Manual review; Codex automation not connected.</p>
    </header>
    {!dashboard.available ? <section className="border-y border-border py-10"><FileSearch className="h-6 w-6 text-muted-foreground" aria-hidden="true" /><h2 className="mt-3 text-lg font-medium">Initial source feed not published</h2><p className="mt-2 max-w-2xl text-sm text-muted-foreground">The register will appear after the source-backed feed has been imported. No compliance verdict or percentage is available.</p></section> : <>
      <dl className="grid gap-4 border-y border-border py-4 sm:grid-cols-2 xl:grid-cols-4"><DetailField label="Scope">FSP app · Delaware incorporation stated; exact legal identity requires evidence</DetailField><DetailField label="Feed checked">{displayDate(dashboard.checkedAt)} · revision {dashboard.revision}</DetailField><DetailField label="Assessment date">{displayDate(dashboard.assessmentAsOf)}</DetailField><DetailField label="Published">{displayDate(dashboard.publishedAt)}</DetailField></dl>
      <nav aria-label="FSP compliance sections" className="flex flex-wrap gap-x-6 gap-y-3 border-b border-border pb-3 text-sm"><a href="#requirements" className="text-primary">Requirement register</a><a href="#facts" className="hover:text-primary">Facts &amp; feature context</a><a href="#sources" className="hover:text-primary">Source library</a><Link href="/legal/policies" className="hover:text-primary">Policies &amp; Procedures</Link></nav>
      <section id="requirements" className="scroll-mt-6 space-y-4"><div className="flex flex-wrap items-baseline justify-between gap-3"><h2 className="text-lg font-semibold">Requirement register</h2><p className="text-xs text-muted-foreground">{dashboard.findings.length} review topics · No automatic sign-off</p></div>
        <dl className="grid grid-cols-2 gap-4 border-y border-border py-4 lg:grid-cols-4">{STATUSES.map((state) => <div key={state}><dt className="text-xs text-muted-foreground">{displayState(state)}</dt><dd className="mt-1 font-mono text-2xl tabular-nums">{dashboard.counts[state]}</dd></div>)}</dl>
        <form action="/legal/compliance/fsp" method="get" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-[minmax(180px,1.5fr)_1fr_1fr_1fr_auto]">
          <EntityField label="Search requirements"><input className={fieldClass} name="q" defaultValue={search} maxLength={200} placeholder="Topic, policy or jurisdiction" /></EntityField>
          <EntityField label="Applicability"><select className={fieldClass} name="status" defaultValue={status}><option value="">All decisions</option>{STATUSES.map((state) => <option key={state} value={state}>{displayState(state)}</option>)}</select></EntityField>
          <EntityField label="Priority"><select className={fieldClass} name="priority" defaultValue={priority}><option value="">All priorities</option>{PRIORITIES.map((item) => <option key={item} value={item}>{displayState(item)}</option>)}</select></EntityField>
          <EntityField label="Review area"><select className={fieldClass} name="category" defaultValue={category}><option value="">All areas</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select></EntityField>
          <div className="flex items-end gap-3"><button type="submit" className="inline-flex min-h-10 items-center gap-2 border border-border px-4 py-2 text-sm hover:bg-muted/50"><ListFilter className="h-3.5 w-3.5" aria-hidden="true" />Filter</button><Link href="/legal/compliance/fsp#requirements" className="py-2 text-xs text-muted-foreground hover:text-foreground">Reset</Link></div>
        </form>
        <p className="text-xs text-muted-foreground">Showing {findings.length} of {dashboard.findings.length}. Expand a requirement to inspect sources, feature evidence and review history.</p>
        <div className="border-y border-border"><div aria-hidden="true" className="hidden grid-cols-[minmax(0,2.4fr)_1fr_0.6fr_1fr_1fr_16px] gap-4 border-b border-border px-4 py-3 text-[11px] font-medium uppercase tracking-wide text-muted-foreground lg:grid"><span>Requirement / jurisdiction</span><span>Applicability</span><span>Priority</span><span>Control</span><span>Legal review</span><span /></div>
          {!findings.length && <p className="px-4 py-8 text-sm text-muted-foreground">No requirements match these filters. Reset the filters to view the full register.</p>}
          {findings.map((finding) => <details key={`${dashboard.assessmentId}-${finding.rule.id}`} id={`requirement-${finding.rule.id}`} className="group scroll-mt-6 border-b border-border last:border-b-0">
            <summary className="relative grid cursor-pointer list-none grid-cols-1 items-start gap-3 py-4 pl-4 pr-10 hover:bg-muted/30 focus-visible:outline-2 focus-visible:outline-ring sm:grid-cols-[minmax(0,1fr)_1fr] lg:grid-cols-[minmax(0,2.4fr)_1fr_0.6fr_1fr_1fr] lg:gap-4 [&::-webkit-details-marker]:hidden">
              <span className="min-w-0"><span className="block text-sm font-medium leading-relaxed">{finding.rule.title}</span><span className="mt-1 block text-xs text-muted-foreground">{finding.rule.category} · {finding.rule.jurisdiction}</span></span>
              <span className="flex flex-wrap items-center gap-x-3 gap-y-1 lg:block"><StateLabel value={finding.status} /><span className="lg:hidden"><StateLabel value={finding.rule.priority} /></span><span className="text-xs text-muted-foreground lg:hidden">Control: {displayState(finding.controlStatus)}</span></span>
              <span className="hidden lg:block"><StateLabel value={finding.rule.priority} /></span><span className="hidden lg:block"><StateLabel value={finding.controlStatus} /></span><span className="hidden text-xs text-muted-foreground lg:block">{finding.decision ? displayDate(finding.decision.reviewOn) : 'Not set'}<span className="mt-1 block">{finding.decision?.owner || 'Unassigned'}</span></span>
              <ChevronDown className="absolute right-4 top-5 h-4 w-4 text-muted-foreground group-open:rotate-180" aria-hidden="true" />
            </summary><FindingDetails finding={finding} dashboard={dashboard} />
          </details>)}
        </div>
      </section>
      <section id="facts" className="scroll-mt-6 space-y-4 border-t border-border pt-6"><h2 className="text-lg font-semibold">Facts &amp; feature context</h2><p className="max-w-3xl text-sm leading-relaxed text-muted-foreground">Code shows capabilities. Locations, thresholds, legal identity and live behavior require separate evidence. Updating a fact creates a new assessment for legal review.</p><div className="divide-y divide-border">{dashboard.facts.map((fact) => <details key={`${dashboard.snapshotId}-${fact.key}`} id={`fact-${fact.key}`} className="scroll-mt-6 py-4"><summary className="cursor-pointer text-sm font-medium"><span>{fact.label}</span><span className="ml-3 text-xs font-normal text-muted-foreground">{displayState(fact.value)} · {fact.certainty === 'SOURCE_SIGNAL' ? 'Source capability only' : displayState(fact.certainty)}</span></summary><div className="mt-4 space-y-3 pl-4"><p className="text-sm leading-relaxed">{fact.detail}</p><p className="text-xs text-muted-foreground">Review due {displayDate(fact.reviewOn)}</p><ul className="space-y-2 text-xs">{dashboard.sources.filter((source) => fact.sourceIds.includes(source.id)).map((source) => <li key={source.id}><EvidenceLink url={source.url}>{source.title}</EvidenceLink><span className="ml-2 text-muted-foreground">Checked {displayDate(source.checkedAt)}</span></li>)}</ul>{dashboard.canWrite && dashboard.snapshotId && <details><summary className="cursor-pointer text-xs text-primary">Update this fact with evidence</summary><FactForm snapshotId={dashboard.snapshotId} fact={fact} /></details>}</div></details>)}</div></section>
      <section id="sources" className="scroll-mt-6 space-y-4 border-t border-border pt-6"><h2 className="text-lg font-semibold">Source library</h2><p className="text-sm text-muted-foreground">Primary legal sources and pinned app evidence used in this feed. Checked dates show source review, not compliance certification.</p><div className="grid gap-x-8 md:grid-cols-2">{dashboard.sources.map((source) => <article key={source.id} id={`source-${source.id}`} className="min-w-0 space-y-2 border-b border-border py-4"><div className="text-sm"><EvidenceLink url={source.url}>{source.title}</EvidenceLink></div><p className="text-xs text-muted-foreground">{displayState(source.kind)} · Checked {displayDate(source.checkedAt)}</p>{source.note && <p className="text-xs leading-relaxed text-muted-foreground">{source.note}</p>}</article>)}</div></section>
      <footer className="space-y-2 border-t border-border pt-4 text-xs text-muted-foreground"><p>Legal OS holds applicability decisions and review history. {dashboard.cisoEnabled ? 'Approved controls can be queued to CISO Assistant; a queue receipt is separate from delivery.' : 'CISO control synchronization is not enabled.'}</p><p>This initial feed is a review inventory. Missing evidence remains visible and legal scope must be maintained as the app changes.</p>{dashboard.feedHash && <details><summary className="cursor-pointer">Feed provenance</summary><p className="mt-2 break-all font-mono">SHA-256 {dashboard.feedHash}</p></details>}</footer>
    </>}
  </div>
}
